// internal/proto/coordinator/coordinator.proto
// Protocol Buffers definition for worker-coordinator communication

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: internal/proto/coordinator/v1/coordinator.proto

package coordinator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterWorkerRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	WorkerId           string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	MaxConcurrentTasks int32                  `protobuf:"varint,2,opt,name=max_concurrent_tasks,json=maxConcurrentTasks,proto3" json:"max_concurrent_tasks,omitempty"`
	Capabilities       map[string]string      `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // e.g., {"circuits": "merkle,range,addition"}
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RegisterWorkerRequest) Reset() {
	*x = RegisterWorkerRequest{}
	mi := &file_internal_proto_coordinator_v1_coordinator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerRequest) ProtoMessage() {}

func (x *RegisterWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_coordinator_v1_coordinator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerRequest.ProtoReflect.Descriptor instead.
func (*RegisterWorkerRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterWorkerRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *RegisterWorkerRequest) GetMaxConcurrentTasks() int32 {
	if x != nil {
		return x.MaxConcurrentTasks
	}
	return 0
}

func (x *RegisterWorkerRequest) GetCapabilities() map[string]string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type RegisterWorkerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWorkerResponse) Reset() {
	*x = RegisterWorkerResponse{}
	mi := &file_internal_proto_coordinator_v1_coordinator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerResponse) ProtoMessage() {}

func (x *RegisterWorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_coordinator_v1_coordinator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerResponse.ProtoReflect.Descriptor instead.
func (*RegisterWorkerResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterWorkerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterWorkerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_internal_proto_coordinator_v1_coordinator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_coordinator_v1_coordinator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_internal_proto_coordinator_v1_coordinator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_coordinator_v1_coordinator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ReceiveTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveTasksRequest) Reset() {
	*x = ReceiveTasksRequest{}
	mi := &file_internal_proto_coordinator_v1_coordinator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveTasksRequest) ProtoMessage() {}

func (x *ReceiveTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_coordinator_v1_coordinator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveTasksRequest.ProtoReflect.Descriptor instead.
func (*ReceiveTasksRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{4}
}

func (x *ReceiveTasksRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type TaskAssignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	CircuitType   string                 `protobuf:"bytes,2,opt,name=circuit_type,json=circuitType,proto3" json:"circuit_type,omitempty"`         // "merkle_proof", "range_proof", etc.
	InputDataJson []byte                 `protobuf:"bytes,3,opt,name=input_data_json,json=inputDataJson,proto3" json:"input_data_json,omitempty"` // JSON-encoded input data
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`              // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskAssignment) Reset() {
	*x = TaskAssignment{}
	mi := &file_internal_proto_coordinator_v1_coordinator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskAssignment) ProtoMessage() {}

func (x *TaskAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_coordinator_v1_coordinator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskAssignment.ProtoReflect.Descriptor instead.
func (*TaskAssignment) Descriptor() ([]byte, []int) {
	return file_internal_proto_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{5}
}

func (x *TaskAssignment) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskAssignment) GetCircuitType() string {
	if x != nil {
		return x.CircuitType
	}
	return ""
}

func (x *TaskAssignment) GetInputDataJson() []byte {
	if x != nil {
		return x.InputDataJson
	}
	return nil
}

func (x *TaskAssignment) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type StartTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	WorkerId      string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTaskRequest) Reset() {
	*x = StartTaskRequest{}
	mi := &file_internal_proto_coordinator_v1_coordinator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTaskRequest) ProtoMessage() {}

func (x *StartTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_coordinator_v1_coordinator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTaskRequest.ProtoReflect.Descriptor instead.
func (*StartTaskRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{6}
}

func (x *StartTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *StartTaskRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type StartTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTaskResponse) Reset() {
	*x = StartTaskResponse{}
	mi := &file_internal_proto_coordinator_v1_coordinator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTaskResponse) ProtoMessage() {}

func (x *StartTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_coordinator_v1_coordinator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTaskResponse.ProtoReflect.Descriptor instead.
func (*StartTaskResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{7}
}

func (x *StartTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StartTaskResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TaskCompletionRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TaskId            string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	WorkerId          string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	ProofData         []byte                 `protobuf:"bytes,3,opt,name=proof_data,json=proofData,proto3" json:"proof_data,omitempty"`                           // Serialized gnark proof
	ProofMetadataJson []byte                 `protobuf:"bytes,4,opt,name=proof_metadata_json,json=proofMetadataJson,proto3" json:"proof_metadata_json,omitempty"` // JSON-encoded metadata
	MerkleRoot        string                 `protobuf:"bytes,5,opt,name=merkle_root,json=merkleRoot,proto3" json:"merkle_root,omitempty"`                        // Optional, for Merkle proofs
	DurationMs        int64                  `protobuf:"varint,6,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`                       // How long proof took to generate
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TaskCompletionRequest) Reset() {
	*x = TaskCompletionRequest{}
	mi := &file_internal_proto_coordinator_v1_coordinator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskCompletionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskCompletionRequest) ProtoMessage() {}

func (x *TaskCompletionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_coordinator_v1_coordinator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskCompletionRequest.ProtoReflect.Descriptor instead.
func (*TaskCompletionRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{8}
}

func (x *TaskCompletionRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskCompletionRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *TaskCompletionRequest) GetProofData() []byte {
	if x != nil {
		return x.ProofData
	}
	return nil
}

func (x *TaskCompletionRequest) GetProofMetadataJson() []byte {
	if x != nil {
		return x.ProofMetadataJson
	}
	return nil
}

func (x *TaskCompletionRequest) GetMerkleRoot() string {
	if x != nil {
		return x.MerkleRoot
	}
	return ""
}

func (x *TaskCompletionRequest) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type TaskCompletionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskCompletionResponse) Reset() {
	*x = TaskCompletionResponse{}
	mi := &file_internal_proto_coordinator_v1_coordinator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskCompletionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskCompletionResponse) ProtoMessage() {}

func (x *TaskCompletionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_coordinator_v1_coordinator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskCompletionResponse.ProtoReflect.Descriptor instead.
func (*TaskCompletionResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{9}
}

func (x *TaskCompletionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TaskCompletionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TaskFailureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	WorkerId      string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskFailureRequest) Reset() {
	*x = TaskFailureRequest{}
	mi := &file_internal_proto_coordinator_v1_coordinator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskFailureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskFailureRequest) ProtoMessage() {}

func (x *TaskFailureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_coordinator_v1_coordinator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskFailureRequest.ProtoReflect.Descriptor instead.
func (*TaskFailureRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{10}
}

func (x *TaskFailureRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskFailureRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *TaskFailureRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type TaskFailureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskFailureResponse) Reset() {
	*x = TaskFailureResponse{}
	mi := &file_internal_proto_coordinator_v1_coordinator_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskFailureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskFailureResponse) ProtoMessage() {}

func (x *TaskFailureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_coordinator_v1_coordinator_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskFailureResponse.ProtoReflect.Descriptor instead.
func (*TaskFailureResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{11}
}

func (x *TaskFailureResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TaskFailureResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_internal_proto_coordinator_v1_coordinator_proto protoreflect.FileDescriptor

const file_internal_proto_coordinator_v1_coordinator_proto_rawDesc = "" +
	"\n" +
	"/internal/proto/coordinator/v1/coordinator.proto\x12\vcoordinator\"\x81\x02\n" +
	"\x15RegisterWorkerRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x120\n" +
	"\x14max_concurrent_tasks\x18\x02 \x01(\x05R\x12maxConcurrentTasks\x12X\n" +
	"\fcapabilities\x18\x03 \x03(\v24.coordinator.RegisterWorkerRequest.CapabilitiesEntryR\fcapabilities\x1a?\n" +
	"\x11CapabilitiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"L\n" +
	"\x16RegisterWorkerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"M\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"-\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"2\n" +
	"\x13ReceiveTasksRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\"\x93\x01\n" +
	"\x0eTaskAssignment\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12!\n" +
	"\fcircuit_type\x18\x02 \x01(\tR\vcircuitType\x12&\n" +
	"\x0finput_data_json\x18\x03 \x01(\fR\rinputDataJson\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\"H\n" +
	"\x10StartTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\"G\n" +
	"\x11StartTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xde\x01\n" +
	"\x15TaskCompletionRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12\x1d\n" +
	"\n" +
	"proof_data\x18\x03 \x01(\fR\tproofData\x12.\n" +
	"\x13proof_metadata_json\x18\x04 \x01(\fR\x11proofMetadataJson\x12\x1f\n" +
	"\vmerkle_root\x18\x05 \x01(\tR\n" +
	"merkleRoot\x12\x1f\n" +
	"\vduration_ms\x18\x06 \x01(\x03R\n" +
	"durationMs\"L\n" +
	"\x16TaskCompletionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"o\n" +
	"\x12TaskFailureRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"I\n" +
	"\x13TaskFailureResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x8d\x04\n" +
	"\x12CoordinatorService\x12Y\n" +
	"\x0eRegisterWorker\x12\".coordinator.RegisterWorkerRequest\x1a#.coordinator.RegisterWorkerResponse\x12N\n" +
	"\rSendHeartbeat\x12\x1d.coordinator.HeartbeatRequest\x1a\x1e.coordinator.HeartbeatResponse\x12J\n" +
	"\tStartTask\x12\x1d.coordinator.StartTaskRequest\x1a\x1e.coordinator.StartTaskResponse\x12[\n" +
	"\x10ReportCompletion\x12\".coordinator.TaskCompletionRequest\x1a#.coordinator.TaskCompletionResponse\x12R\n" +
	"\rReportFailure\x12\x1f.coordinator.TaskFailureRequest\x1a .coordinator.TaskFailureResponse\x12O\n" +
	"\fReceiveTasks\x12 .coordinator.ReceiveTasksRequest\x1a\x1b.coordinator.TaskAssignment0\x01BJZHgithub.com/saiweb3dev/distributed-zkp-network/internal/proto/coordinatorb\x06proto3"

var (
	file_internal_proto_coordinator_v1_coordinator_proto_rawDescOnce sync.Once
	file_internal_proto_coordinator_v1_coordinator_proto_rawDescData []byte
)

func file_internal_proto_coordinator_v1_coordinator_proto_rawDescGZIP() []byte {
	file_internal_proto_coordinator_v1_coordinator_proto_rawDescOnce.Do(func() {
		file_internal_proto_coordinator_v1_coordinator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_coordinator_v1_coordinator_proto_rawDesc), len(file_internal_proto_coordinator_v1_coordinator_proto_rawDesc)))
	})
	return file_internal_proto_coordinator_v1_coordinator_proto_rawDescData
}

var file_internal_proto_coordinator_v1_coordinator_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_internal_proto_coordinator_v1_coordinator_proto_goTypes = []any{
	(*RegisterWorkerRequest)(nil),  // 0: coordinator.RegisterWorkerRequest
	(*RegisterWorkerResponse)(nil), // 1: coordinator.RegisterWorkerResponse
	(*HeartbeatRequest)(nil),       // 2: coordinator.HeartbeatRequest
	(*HeartbeatResponse)(nil),      // 3: coordinator.HeartbeatResponse
	(*ReceiveTasksRequest)(nil),    // 4: coordinator.ReceiveTasksRequest
	(*TaskAssignment)(nil),         // 5: coordinator.TaskAssignment
	(*StartTaskRequest)(nil),       // 6: coordinator.StartTaskRequest
	(*StartTaskResponse)(nil),      // 7: coordinator.StartTaskResponse
	(*TaskCompletionRequest)(nil),  // 8: coordinator.TaskCompletionRequest
	(*TaskCompletionResponse)(nil), // 9: coordinator.TaskCompletionResponse
	(*TaskFailureRequest)(nil),     // 10: coordinator.TaskFailureRequest
	(*TaskFailureResponse)(nil),    // 11: coordinator.TaskFailureResponse
	nil,                            // 12: coordinator.RegisterWorkerRequest.CapabilitiesEntry
}
var file_internal_proto_coordinator_v1_coordinator_proto_depIdxs = []int32{
	12, // 0: coordinator.RegisterWorkerRequest.capabilities:type_name -> coordinator.RegisterWorkerRequest.CapabilitiesEntry
	0,  // 1: coordinator.CoordinatorService.RegisterWorker:input_type -> coordinator.RegisterWorkerRequest
	2,  // 2: coordinator.CoordinatorService.SendHeartbeat:input_type -> coordinator.HeartbeatRequest
	6,  // 3: coordinator.CoordinatorService.StartTask:input_type -> coordinator.StartTaskRequest
	8,  // 4: coordinator.CoordinatorService.ReportCompletion:input_type -> coordinator.TaskCompletionRequest
	10, // 5: coordinator.CoordinatorService.ReportFailure:input_type -> coordinator.TaskFailureRequest
	4,  // 6: coordinator.CoordinatorService.ReceiveTasks:input_type -> coordinator.ReceiveTasksRequest
	1,  // 7: coordinator.CoordinatorService.RegisterWorker:output_type -> coordinator.RegisterWorkerResponse
	3,  // 8: coordinator.CoordinatorService.SendHeartbeat:output_type -> coordinator.HeartbeatResponse
	7,  // 9: coordinator.CoordinatorService.StartTask:output_type -> coordinator.StartTaskResponse
	9,  // 10: coordinator.CoordinatorService.ReportCompletion:output_type -> coordinator.TaskCompletionResponse
	11, // 11: coordinator.CoordinatorService.ReportFailure:output_type -> coordinator.TaskFailureResponse
	5,  // 12: coordinator.CoordinatorService.ReceiveTasks:output_type -> coordinator.TaskAssignment
	7,  // [7:13] is the sub-list for method output_type
	1,  // [1:7] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_internal_proto_coordinator_v1_coordinator_proto_init() }
func file_internal_proto_coordinator_v1_coordinator_proto_init() {
	if File_internal_proto_coordinator_v1_coordinator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_coordinator_v1_coordinator_proto_rawDesc), len(file_internal_proto_coordinator_v1_coordinator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_coordinator_v1_coordinator_proto_goTypes,
		DependencyIndexes: file_internal_proto_coordinator_v1_coordinator_proto_depIdxs,
		MessageInfos:      file_internal_proto_coordinator_v1_coordinator_proto_msgTypes,
	}.Build()
	File_internal_proto_coordinator_v1_coordinator_proto = out.File
	file_internal_proto_coordinator_v1_coordinator_proto_goTypes = nil
	file_internal_proto_coordinator_v1_coordinator_proto_depIdxs = nil
}
