// internal/proto/coordinator/coordinator.proto
// Protocol Buffers definition for worker-coordinator communication

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.29.3
// source: internal/proto/coordinator/v1/coordinator.proto

package coordinator

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CoordinatorService_RegisterWorker_FullMethodName   = "/coordinator.CoordinatorService/RegisterWorker"
	CoordinatorService_SendHeartbeat_FullMethodName    = "/coordinator.CoordinatorService/SendHeartbeat"
	CoordinatorService_StartTask_FullMethodName        = "/coordinator.CoordinatorService/StartTask"
	CoordinatorService_ReportCompletion_FullMethodName = "/coordinator.CoordinatorService/ReportCompletion"
	CoordinatorService_ReportFailure_FullMethodName    = "/coordinator.CoordinatorService/ReportFailure"
	CoordinatorService_ReceiveTasks_FullMethodName     = "/coordinator.CoordinatorService/ReceiveTasks"
)

// CoordinatorServiceClient is the client API for CoordinatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoordinatorServiceClient interface {
	// Worker registration - called once when worker starts
	RegisterWorker(ctx context.Context, in *RegisterWorkerRequest, opts ...grpc.CallOption) (*RegisterWorkerResponse, error)
	// Heartbeat - called every 5 seconds to signal worker is alive
	SendHeartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// Start task - called when worker begins processing a task
	StartTask(ctx context.Context, in *StartTaskRequest, opts ...grpc.CallOption) (*StartTaskResponse, error)
	// Report task completion - called when proof generation succeeds
	ReportCompletion(ctx context.Context, in *TaskCompletionRequest, opts ...grpc.CallOption) (*TaskCompletionResponse, error)
	// Report task failure - called when proof generation fails
	ReportFailure(ctx context.Context, in *TaskFailureRequest, opts ...grpc.CallOption) (*TaskFailureResponse, error)
	// Receive tasks - server-streaming RPC where coordinator pushes tasks to worker
	ReceiveTasks(ctx context.Context, in *ReceiveTasksRequest, opts ...grpc.CallOption) (CoordinatorService_ReceiveTasksClient, error)
}

type coordinatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCoordinatorServiceClient(cc grpc.ClientConnInterface) CoordinatorServiceClient {
	return &coordinatorServiceClient{cc}
}

func (c *coordinatorServiceClient) RegisterWorker(ctx context.Context, in *RegisterWorkerRequest, opts ...grpc.CallOption) (*RegisterWorkerResponse, error) {
	out := new(RegisterWorkerResponse)
	err := c.cc.Invoke(ctx, CoordinatorService_RegisterWorker_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) SendHeartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, CoordinatorService_SendHeartbeat_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) StartTask(ctx context.Context, in *StartTaskRequest, opts ...grpc.CallOption) (*StartTaskResponse, error) {
	out := new(StartTaskResponse)
	err := c.cc.Invoke(ctx, CoordinatorService_StartTask_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) ReportCompletion(ctx context.Context, in *TaskCompletionRequest, opts ...grpc.CallOption) (*TaskCompletionResponse, error) {
	out := new(TaskCompletionResponse)
	err := c.cc.Invoke(ctx, CoordinatorService_ReportCompletion_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) ReportFailure(ctx context.Context, in *TaskFailureRequest, opts ...grpc.CallOption) (*TaskFailureResponse, error) {
	out := new(TaskFailureResponse)
	err := c.cc.Invoke(ctx, CoordinatorService_ReportFailure_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) ReceiveTasks(ctx context.Context, in *ReceiveTasksRequest, opts ...grpc.CallOption) (CoordinatorService_ReceiveTasksClient, error) {
	stream, err := c.cc.NewStream(ctx, &CoordinatorService_ServiceDesc.Streams[0], CoordinatorService_ReceiveTasks_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &coordinatorServiceReceiveTasksClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CoordinatorService_ReceiveTasksClient interface {
	Recv() (*TaskAssignment, error)
	grpc.ClientStream
}

type coordinatorServiceReceiveTasksClient struct {
	grpc.ClientStream
}

func (x *coordinatorServiceReceiveTasksClient) Recv() (*TaskAssignment, error) {
	m := new(TaskAssignment)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CoordinatorServiceServer is the server API for CoordinatorService service.
// All implementations must embed UnimplementedCoordinatorServiceServer
// for forward compatibility
type CoordinatorServiceServer interface {
	// Worker registration - called once when worker starts
	RegisterWorker(context.Context, *RegisterWorkerRequest) (*RegisterWorkerResponse, error)
	// Heartbeat - called every 5 seconds to signal worker is alive
	SendHeartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// Start task - called when worker begins processing a task
	StartTask(context.Context, *StartTaskRequest) (*StartTaskResponse, error)
	// Report task completion - called when proof generation succeeds
	ReportCompletion(context.Context, *TaskCompletionRequest) (*TaskCompletionResponse, error)
	// Report task failure - called when proof generation fails
	ReportFailure(context.Context, *TaskFailureRequest) (*TaskFailureResponse, error)
	// Receive tasks - server-streaming RPC where coordinator pushes tasks to worker
	ReceiveTasks(*ReceiveTasksRequest, CoordinatorService_ReceiveTasksServer) error
	mustEmbedUnimplementedCoordinatorServiceServer()
}

// UnimplementedCoordinatorServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCoordinatorServiceServer struct {
}

func (UnimplementedCoordinatorServiceServer) RegisterWorker(context.Context, *RegisterWorkerRequest) (*RegisterWorkerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterWorker not implemented")
}
func (UnimplementedCoordinatorServiceServer) SendHeartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendHeartbeat not implemented")
}
func (UnimplementedCoordinatorServiceServer) StartTask(context.Context, *StartTaskRequest) (*StartTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartTask not implemented")
}
func (UnimplementedCoordinatorServiceServer) ReportCompletion(context.Context, *TaskCompletionRequest) (*TaskCompletionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportCompletion not implemented")
}
func (UnimplementedCoordinatorServiceServer) ReportFailure(context.Context, *TaskFailureRequest) (*TaskFailureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportFailure not implemented")
}
func (UnimplementedCoordinatorServiceServer) ReceiveTasks(*ReceiveTasksRequest, CoordinatorService_ReceiveTasksServer) error {
	return status.Errorf(codes.Unimplemented, "method ReceiveTasks not implemented")
}
func (UnimplementedCoordinatorServiceServer) mustEmbedUnimplementedCoordinatorServiceServer() {}

// UnsafeCoordinatorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoordinatorServiceServer will
// result in compilation errors.
type UnsafeCoordinatorServiceServer interface {
	mustEmbedUnimplementedCoordinatorServiceServer()
}

func RegisterCoordinatorServiceServer(s grpc.ServiceRegistrar, srv CoordinatorServiceServer) {
	s.RegisterService(&CoordinatorService_ServiceDesc, srv)
}

func _CoordinatorService_RegisterWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterWorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).RegisterWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_RegisterWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).RegisterWorker(ctx, req.(*RegisterWorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_SendHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).SendHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_SendHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).SendHeartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_StartTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).StartTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_StartTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).StartTask(ctx, req.(*StartTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_ReportCompletion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskCompletionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).ReportCompletion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_ReportCompletion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).ReportCompletion(ctx, req.(*TaskCompletionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_ReportFailure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskFailureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).ReportFailure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_ReportFailure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).ReportFailure(ctx, req.(*TaskFailureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_ReceiveTasks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReceiveTasksRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CoordinatorServiceServer).ReceiveTasks(m, &coordinatorServiceReceiveTasksServer{stream})
}

type CoordinatorService_ReceiveTasksServer interface {
	Send(*TaskAssignment) error
	grpc.ServerStream
}

type coordinatorServiceReceiveTasksServer struct {
	grpc.ServerStream
}

func (x *coordinatorServiceReceiveTasksServer) Send(m *TaskAssignment) error {
	return x.ServerStream.SendMsg(m)
}

// CoordinatorService_ServiceDesc is the grpc.ServiceDesc for CoordinatorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoordinatorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "coordinator.CoordinatorService",
	HandlerType: (*CoordinatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterWorker",
			Handler:    _CoordinatorService_RegisterWorker_Handler,
		},
		{
			MethodName: "SendHeartbeat",
			Handler:    _CoordinatorService_SendHeartbeat_Handler,
		},
		{
			MethodName: "StartTask",
			Handler:    _CoordinatorService_StartTask_Handler,
		},
		{
			MethodName: "ReportCompletion",
			Handler:    _CoordinatorService_ReportCompletion_Handler,
		},
		{
			MethodName: "ReportFailure",
			Handler:    _CoordinatorService_ReportFailure_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReceiveTasks",
			Handler:       _CoordinatorService_ReceiveTasks_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/proto/coordinator/v1/coordinator.proto",
}
